### ISSUE TITLE
How to amplify a low volume sound?

### ISSUE THREAD

**Issue by mariosant** [VJAI/musquito#10]
Hi there! I have a rather simplistic case where I need to amplify the audio beyond of what volume property provides. I was wondering if there is a way to do that.

My case goes like this:
```
const sound = buzz({
       src: props.src,
       loop: true
})
```

**Comment by VJAI** [comment]
You could do something like this,

```
const sound = buzz({
       src: props.src,
       loop: true
})
sound._gainNode.gain.value = 1;
```

Please give a star to the repo if you like that'll encourage me to spend to more time with it.

**Comment by mariosant** [comment]
Thank you @VJAI ! Just starred it.
