### ISSUE TITLE
Google Chrome 70

### ISSUE THREAD

**Issue by zeronbilgisayar** [VJAI/musquito#2]
Hello. The console started to give warning today.

The web audio autoplay policy will be re-enabled in Chrome 70 (October 2018). 
Will this autoplay be a problem using musquito-1.0.2.js? Any way to fix this warning?

Detail: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

thanks.

**Comment by VJAI** [comment]
Sorry for the delay. I've made a fix for this issue (v1.1.2). musquito will auto-enable the audio on user's first interaction. I've yet to deploy to npm. I'll do a round of test and do it by tomorrow.
