### ISSUE TITLE
Event handlers never get fired

### ISSUE THREAD

**Issue by JimVercoelen** [VJAI/musquito#3]

**Comment by VJAI** [comment]
No events are getting fired? It would be of great help if you post some code. Anyway I'll do a round of testing from my side.

**Comment by VJAI** [comment]
I can reproduce it. Will have a fix by today.

**Comment by VJAI** [comment]
@JimVercoelen The fix is applied and available in 1.1.1.

**Comment by JimVercoelen** [comment]
@VJAI awesome!
