### ISSUE TITLE
Cannot get Musquito to accept a data URI

### ISSUE THREAD

**Issue by chadananda** [VJAI/musquito#5]
Here's a little jsfiddle demonstrating that a data URI does not play:

    https://jsfiddle.net/chadananda/aqpdLs0b/

**Comment by VJAI** [comment]
Thanks for letting me know. Will look into it tomorrow and update you ASAP.

**Comment by VJAI** [comment]
This is fixed and available in 1.1.4. Please install latest version from npm and verify.

**Comment by chadananda** [comment]
Works correctly now:  https://jsfiddle.net/chadananda/aqpdLs0b/

**Comment by VJAI** [comment]
@chadananda Please give a star if you like the library that will motivate me to spend more time and do some improvements :)
