### ISSUE TITLE
I tired the percent loaded but I get errors

### ISSUE THREAD

**Issue by kyoukhana** [VJAI/musquito#9]
Thanks for the help but I tried the percent loaded code that you provided here

https://github.com/VJAI/musquito/issues/7

But I am getting errors in the console.  

```
Error in v-on handler: "Error: You should pass the source for the audio."
```

Here is the link to the repo

https://github.com/kyoukhana/audiotest

**Comment by VJAI** [comment]
You've a line like `var buzz = $buzz()` remove it and that's not required.

All you need is,

```
$buzz.setup();
$buzz.load('https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3', function(evtData){
	console.log(evtData.url);
	console.log(evtData.percentageDownloaded);
});
```

**Comment by kyoukhana** [comment]
I tried the following code 

```
const buzz = $buzz({
    url: 'sounds/bg.mp3',
    onloadprogress: function(percentage) {
       console.log(percentage);
    }
});

```
But it throws a error in the console.  Try pulling the repo and try it

https://github.com/kyoukhana/audiotest

**Comment by VJAI** [comment]
My bad it's not `url` but `src`. http://musquitojs.com/

**Comment by kyoukhana** [comment]
No problem.  I got it working in this example 

```
 const buzz = $buzz({
      src: 'https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3',
      onloadprogress: function(percentage) {
         console.log(percentage);
      }
      });

      buzz.play();
```

But this example isn't working am I missing something.

```
 $buzz.load('https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3', function(evtData) {
        console.log(evtData.url);
        console.log(evtData.percentageDownloaded);
      })

      buzz.play();
```

**Comment by VJAI** [comment]
`$buzz.load` is a static method and you may not be using that too often. An example use case is, let's say you need to preload all the audio resources used in a HTML5 game ahead; you can use that method.

Example

```
$buzz.setup(); // you need to call setup before doing anything in global level.

var promise = $buzz.load(resource1, resource2, resource3);

promise.then(function() {
  console.log('All audio resources are loaded');
});
```

You can also pass the `progressCallback` as the second argument.

```
$buzz.load(resource1, resource2, resource3, progressCallback);
```

**Comment by kyoukhana** [comment]
I tried that says $buzz is not defined 
```
<script>
import HelloWorld from './components/HelloWorld.vue'
import $buzz from 'musquito';

export default {
  name: 'App',
  components: {
    HelloWorld
  },
  methods:{
    play: function (event) {
			// var buzz = $buzz('https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3');
			// console.log(buzz);
      // buzz.play();
      
      // const buzz = $buzz({
      // src: 'https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3',
      // onloadprogress: function(percentage) {
      //    console.log(percentage);
      // }
      // });

      // buzz.play();


        $buzz.setup(); // you need to call setup before doing anything in global level.
        var promise = $buzz.load('https://raw.githubusercontent.com/Tonejs/Tone.js/master/examples/audio/FWDL.mp3');
        promise.then(function() {
            console.log('All audio resources are loaded');
        });


buzz.play();

    }
     }
}
</script>
```

**Comment by VJAI** [comment]
The `buzz.play()` line at last why you have it? I don't think it's required. I tried the above code and I got the message displayed in console. Please go through the documentation http://musquitojs.com

**Comment by kyoukhana** [comment]
My question is how do you play the track once all tracks are loaded.  That is why I had buzz.play()

**Comment by VJAI** [comment]
Good question. You need to again create separate groups calling `$buzz` function.

For example,

Preload all resources.

```
$buzz.setup();

var promise = $buzz.load(resource1, resource2, resource3);

promise.then(function() {
  console.log('All audio resources are loaded');
});
```

To play sounds for "resource1" you need to create a new group. Since all the resources are pre-loaded playing the sound won't loose time in loading the resource.

```
var buzz1 = $buzz({
  src: 'resource1'
});

buzz1.play();
```

Same for other resources.

```
var buzz2 = $buzz({
  src: 'resource2'
});

buzz2.play();
```

**Comment by kyoukhana** [comment]
Got it sorry asking all these questions.  My other question is it possible to just .play() everything that is loaded in too the buffer?

**Comment by VJAI** [comment]
No problem :)

You like to play all the sounds at-once? 

Currently the API not supports that. You need to create separate buzz groups for each resource and then call play in each of them.

**Comment by VJAI** [comment]
For each types of sounds you needed in your app you can create separate buzzes in the starting point.

```
let gunSound, bombSound;

$buzz.setup();

$buzz.load('gun.mp3', 'bomb.mp3').then(function() {
      gunSound = $buzz('gun.mp3');
      bombSound = $buzz('bomb.mp3');
});
```

Now whenever you need to play the gun sound you just call `gunSound.play()`. You can call it multiple times at-once to play multiple gun sounds together.

**Comment by VJAI** [comment]
I just published v3. Playing sounds is very much simplified now. Please checkout the docs.

Simple Example

```
$buzz.play('gun.mp3');
```

Complex Example

```
$buzz.setup({
  src: {
    bg: 'bg.mp3',
    sprite: {
      url: 'sprite.mp3',
      sprite: {
        "beep": [
          0,
          0.48108843537414964
        ],
        "button": [
          2,
          2.4290249433106577
        ],
        "click": [
          4,
          4.672018140589569
        ]
      }
    }
  },
  oninit: () => {
    // Playing sounds with identifiers
    $buzz.play('#bg');
    $buzz.play('#sprite.button');
  }
});
```

**Comment by kyoukhana** [comment]
Awesome will do.  Hopefully the docs have more examples as well.
